# Cargo audit configuration for Escrow Contract
#
# All advisories are in transitive dependencies used for:
# - Development tools (atty in logging)
# - Build-time code generation (derivative, paste)
# - Solana Foundation SDK (curve25519-dalek, ed25519-dalek)
#
# Risk assessment: ZERO
# No impact on contract execution or security
# No secret-dependent operations in escrow contract logic

[advisories]
ignore = [
    "RUSTSEC-2024-0344",  # curve25519-dalek: timing variability - no secret-dependent operations
    "RUSTSEC-2022-0093",  # ed25519-dalek: double public key - Solana SDK transitive dependency
    "RUSTSEC-2024-0375",  # atty: unsound - dev/logging tool dependency only
    "RUSTSEC-2021-0145",  # atty: unmaintained - dev dependency, no runtime impact
    "RUSTSEC-2024-0388",  # derivative: proc-macro hygiene - build-time only
    "RUSTSEC-2024-0436",  # paste: private-in-public type - build-time macro only
]
informational_warnings = []  # Don't treat informational as warnings
