name: Escrow EVM Security Scan

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  security-audit:
    name: Slither & Mythril (EVM Escrow)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ondrix-escrow-evm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.10.0'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ondrix-escrow-evm/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      - name: Hardhat compile (fail-fast)
        run: npx hardhat compile --force

      - name: Install Slither
        run: |
          pip3 install slither-analyzer
          pip3 install solc-select
          solc-select install 0.8.20
          solc-select use 0.8.20

      - name: Install Mythril
        run: |
          pip3 install mythril
        continue-on-error: true

      - name: Run Slither analysis (with remaps & via-IR)
        run: |
          slither contracts \
            --solc-remaps "@openzeppelin/=node_modules/@openzeppelin/ @chainlink/=node_modules/@chainlink/" \
            --solc-args "--base-path . --include-path node_modules --allow-paths .,$GITHUB_WORKSPACE/ondrix-escrow-evm/node_modules --via-ir --optimize --optimize-runs 200" \
            --json slither-report.json || true
          slither contracts \
            --solc-remaps "@openzeppelin/=node_modules/@openzeppelin/ @chainlink/=node_modules/@chainlink/" \
            --solc-args "--base-path . --include-path node_modules --allow-paths .,$GITHUB_WORKSPACE/ondrix-escrow-evm/node_modules --via-ir --optimize --optimize-runs 200" \
            > slither-report.txt 2>&1 || true
        continue-on-error: true

      - name: Run Mythril analysis (analyze compiled bytecode)
        run: |
          echo "Checking artifacts directory..."
          ls -la artifacts/ || echo "No artifacts dir"
          ls -la artifacts/contracts/ || echo "No contracts dir"
          ls -la artifacts/contracts/OndrixEscrow.sol/ || echo "No OndrixEscrow dir"
          
          ARTIFACT=artifacts/contracts/OndrixEscrow.sol/OndrixEscrow.json
          if [ -f "$ARTIFACT" ]; then
            echo "Found artifact: $ARTIFACT"
            BYTECODE=$(jq -r '.deployedBytecode.object // .deployedBytecode // .bytecode.object // .bytecode' "$ARTIFACT")
            echo "Bytecode length: ${#BYTECODE}"
            if [ -z "$BYTECODE" ] || [ "$BYTECODE" = "null" ]; then
              echo "No bytecode found in artifact" >&2
              exit 0
            fi
            myth analyze -c "$BYTECODE" -o json > mythril-report.json 2>&1 || true
            myth analyze -c "$BYTECODE" > mythril-report.txt 2>&1 || true
          else
            echo "Artifact not found: $ARTIFACT" >&2
            echo "Mythril analysis skipped" > mythril-report.txt
            echo "{}" > mythril-report.json
          fi
        continue-on-error: true
        timeout-minutes: 30

      - name: Compile contracts
        run: |
          npx hardhat compile > compile-output.txt 2>&1 || true
        continue-on-error: true

      - name: Run tests
        run: |
          npx hardhat test > test-output.txt 2>&1 || true
        continue-on-error: true

      - name: Upload audit artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: escrow-evm-security-reports
          path: |
            ondrix-escrow-evm/slither-report.json
            ondrix-escrow-evm/slither-report.txt
            ondrix-escrow-evm/mythril-report.json
            ondrix-escrow-evm/mythril-report.txt
            ondrix-escrow-evm/compile-output.txt
            ondrix-escrow-evm/test-output.txt
          retention-days: 30

      - name: Display results summary
        if: always()
        run: |
          echo "=== Slither Summary ==="
          if [ -f slither-report.txt ]; then
            head -n 100 slither-report.txt
          fi
          echo ""
          echo "=== Mythril Summary ==="
          if [ -f mythril-report.txt ]; then
            head -n 50 mythril-report.txt
          fi
